/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_emilianourtechomarioocampo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultTableModel tableModel = new DefaultTableModel();
    Registro registro;
    public Principal() {
        initComponents();
        
        String[] titulos = new String[]{"Row ID", "Order ID", "Order Date", "Costumer ID", "Country", "City", "Product ID", "Sales"};
        tableModel.setColumnIdentifiers(titulos);
        Lt_tabla.setModel(tableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txf_orderID = new javax.swing.JTextField();
        txf_shipMode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txf_segment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_state = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_productID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txf_costumerID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txf_country = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txf_category = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txf_costumerName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txf_city = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txf_region = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txf_subCategory = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txf_productName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        b_agregarRegistro = new javax.swing.JButton();
        ftxf_discount = new javax.swing.JFormattedTextField();
        ftxf_postalCode = new javax.swing.JFormattedTextField();
        ftxf_sale = new javax.swing.JFormattedTextField();
        ftxf_quantity = new javax.swing.JFormattedTextField();
        ftxf_profit = new javax.swing.JFormattedTextField();
        txf_shipDate = new javax.swing.JTextField();
        txf_orderDate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        b_clear = new javax.swing.JButton();
        b_orders = new javax.swing.JButton();
        b_details = new javax.swing.JButton();
        b_costumers = new javax.swing.JButton();
        b_products = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_listar = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        b_eliminarRegistro = new javax.swing.JButton();
        b_updateTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lt_tabla = new javax.swing.JTable();
        pb_carga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Order Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(txf_orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, -1));
        jPanel1.add(txf_shipMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        jLabel2.setText("Ship Mode");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txf_segment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        jLabel3.setText("Segment");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(txf_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        jLabel4.setText("State");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(txf_productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        jLabel5.setText("Product ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setText("Order Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel7.setText("Costumer ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));
        jPanel1.add(txf_costumerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 110, -1));

        jLabel8.setText("Country");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));
        jPanel1.add(txf_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, -1));

        jLabel9.setText("Postal Code");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jLabel10.setText("Category");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));
        jPanel1.add(txf_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, -1));

        jLabel11.setText("Ship Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel12.setText("Costumer Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));
        jPanel1.add(txf_costumerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, -1));

        jLabel13.setText("City");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));
        jPanel1.add(txf_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 110, -1));

        jLabel14.setText("Region");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));
        jPanel1.add(txf_region, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 110, -1));

        jLabel15.setText("Sub-Category");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));
        jPanel1.add(txf_subCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 110, -1));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, -1));

        jLabel16.setText("Order Id");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel17.setText("Ship Mode");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        jLabel18.setText("Segment");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        jLabel19.setText("State");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        jLabel20.setText("Product ID");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        jLabel21.setText("Product Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));
        jPanel1.add(txf_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 560, -1));

        jLabel22.setText("Sale");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel23.setText("Quantity");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel24.setText("Discount");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel25.setText("Profit");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        b_agregarRegistro.setText("Agregar Registro");
        b_agregarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_agregarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarRegistroMouseClicked(evt);
            }
        });
        jPanel1.add(b_agregarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));
        jPanel1.add(ftxf_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 110, -1));
        jPanel1.add(ftxf_postalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 110, -1));

        ftxf_sale.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel1.add(ftxf_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));
        jPanel1.add(ftxf_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 110, -1));

        ftxf_profit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel1.add(ftxf_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, -1));
        jPanel1.add(txf_shipDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, -1));
        jPanel1.add(txf_orderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 130, -1));

        jTabbedPane1.addTab("Agregar Registro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_clear.setText("Clear");
        jPanel2.add(b_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 70, -1));

        b_orders.setText("Orders");
        jPanel2.add(b_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 18, 130, -1));

        b_details.setText("Details");
        jPanel2.add(b_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 18, 130, -1));

        b_costumers.setText("Customers");
        jPanel2.add(b_costumers, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 18, 130, -1));

        b_products.setText("Products");
        jPanel2.add(b_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 18, 130, -1));

        txta_listar.setColumns(20);
        txta_listar.setRows(5);
        jScrollPane1.setViewportView(txta_listar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 660, 240));

        jTabbedPane1.addTab("Listar Registro", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_eliminarRegistro.setText("Eliminar Registro");
        jPanel3.add(b_eliminarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        b_updateTabla.setText("Update Tabla");
        jPanel3.add(b_updateTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 280, -1, -1));

        Lt_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Lt_tabla);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 260));

        jTabbedPane1.addTab("Eliminar Registro", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 670, 340));
        getContentPane().add(pb_carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_agregarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarRegistroMouseClicked
        if (txf_orderID.equals("") || txf_orderDate.equals("") || txf_shipDate.equals("")||
                txf_shipMode.equals("") || txf_costumerID.equals("") || txf_costumerName.equals("")||
                txf_segment.equals("") || txf_country.equals("") || txf_city.equals("") ||
                txf_state.equals("") || ftxf_postalCode.equals("") || txf_region.equals("") || 
                txf_productID.equals("") || txf_category.equals("") || txf_subCategory.equals("") ||
                txf_productName.equals("") || ftxf_sale.equals("") ||
                ftxf_discount.equals("") ||ftxf_profit.equals("") || ftxf_quantity.equals("")){
            
            JOptionPane.showConfirmDialog(this, "Llene todas las casillas por favor");
        }else{            
            registro = new Registro(txf_orderID.getText(), txf_shipMode.getText(), txf_segment.getText(),
            txf_state.getText(), txf_productID.getText(), txf_orderDate.getText(), txf_costumerID.getText(), 
            txf_country.getText(), Integer.parseInt(ftxf_postalCode.getText()), txf_category.getText(), txf_shipDate.getText(),
            txf_costumerName.getText(), txf_city.getText(), txf_region.getText(), txf_subCategory.getText(), ftxf_sale.getText(),
            Integer.parseInt(ftxf_quantity.getText()), Integer.parseInt(ftxf_discount.getText()), Integer.parseInt(ftxf_profit.getText()),
            txf_productName.getText());
            
            listaRegistro.add(registro);
            
            Dba db = new Dba("./TenRecord.accdb");
            db.conectar();
            try {
                int q,d, post;
                String p, oID, sM, s, st, pID, oD, cID, c, cat, sD, cN, city, r, subC, sales, pN;
                //INT
                q = Integer.parseInt(ftxf_quantity.getText());
                d = Integer.parseInt(ftxf_discount.getText());
                p =ftxf_profit.getText();
                post = Integer.parseInt(ftxf_postalCode.getText());     
                //STRING
                oID = txf_orderID.getText();
                sM = txf_shipMode.getText();
                s = txf_segment.getText();
                st = txf_state.getText();
                pID = txf_productID.getText();
                oD = txf_orderDate.getText();
                cID = txf_costumerID.getText();
                c = txf_country.getText();
                cat = txf_category.getText();
                sD = txf_shipDate.getText();
                cN = txf_costumerName.getText();
                city = txf_city.getText();
                r = txf_region.getText();
                subC= txf_subCategory.getText();
                sales = ftxf_sale.getText();
                pN = txf_productName.getText();
                
                db.query.execute("INSERT INTO TenRecord"
                +"(F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21)"
                + "VALUES ('"+ oID+ "', '"+ oD +"', '"+sD+"', '"+sM+"', '"+ cID+"', '"+ cN+"', '"+ s +"', '" + c +"', '"+city+"', '"+st+"', '"+post+"', '"+ r+ "', '"+pID+"', '"+cat+"', '"+subC+"', '"+ pN +"', '" +sales+"', '"+q+"', '"+d+"', '"+p+"')");
                db.commit();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se pudo completar la operacion");
                e.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_b_agregarRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    
    ArrayList<Registro> listaRegistro = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Lt_tabla;
    private javax.swing.JButton b_agregarRegistro;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_costumers;
    private javax.swing.JButton b_details;
    private javax.swing.JButton b_eliminarRegistro;
    private javax.swing.JButton b_orders;
    private javax.swing.JButton b_products;
    private javax.swing.JButton b_updateTabla;
    private javax.swing.JFormattedTextField ftxf_discount;
    private javax.swing.JFormattedTextField ftxf_postalCode;
    private javax.swing.JFormattedTextField ftxf_profit;
    private javax.swing.JFormattedTextField ftxf_quantity;
    private javax.swing.JFormattedTextField ftxf_sale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JProgressBar pb_carga;
    private javax.swing.JTextField txf_category;
    private javax.swing.JTextField txf_city;
    private javax.swing.JTextField txf_costumerID;
    private javax.swing.JTextField txf_costumerName;
    private javax.swing.JTextField txf_country;
    private javax.swing.JTextField txf_orderDate;
    private javax.swing.JTextField txf_orderID;
    private javax.swing.JTextField txf_productID;
    private javax.swing.JTextField txf_productName;
    private javax.swing.JTextField txf_region;
    private javax.swing.JTextField txf_segment;
    private javax.swing.JTextField txf_shipDate;
    private javax.swing.JTextField txf_shipMode;
    private javax.swing.JTextField txf_state;
    private javax.swing.JTextField txf_subCategory;
    private javax.swing.JTextArea txta_listar;
    // End of variables declaration//GEN-END:variables
}
